[package]
name = "lmviewer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "lmv"
path = "src/main.rs"

[dependencies]
ffmpeg-next.workspace = true
pipewire.workspace = true
clap = { version = "4.6.1", features = ["derive"] }
iced.workspace = true
lmv = { path = "../lmv", features = ["iced"] }
time = { version = "0.3.47", features = ["macros"] }
tokio = { version = "1.52.3", features = ["sync", "time"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "local-time",
  "time",
] }
