[package]
name = "gilia"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "gilia"
path = "src/main.rs"
required-features = ["bin"]

[features]
iced = ["dep:iced", "dep:gilia-iced"]
bin = [
  "iced",
  "dep:clap",
  "dep:time",
  "dep:tokio",
  "dep:tracing",
  "dep:tracing-subscriber",
]

[dependencies]
clap = { version = "4.6.1", features = ["derive"], optional = true }
gilia-engine.workspace = true
gilia-iced = { path = "../gilia-iced", optional = true }
iced = { workspace = true, optional = true }
time = { version = "0.3.47", features = ["macros"], optional = true }
tokio = { version = "1.52.3", features = ["sync", "time"], optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "local-time",
  "time",
], optional = true }
