[package]
name = "lmv"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ffmpeg-next.workspace = true
lmv-engine.workspace = true
pipewire.workspace = true
tracing.workspace = true
lmv-iced = { path = "../lmv-iced", optional = true }

[features]
iced = ["dep:lmv-iced"]
